AllCops:
  NewCops: enable
  Exclude:
    - tests/*.rb
    - vendor/**/*
  TargetRubyVersion: 2.5
Metrics/BlockLength:
  Max: 75
Metrics/MethodLength:
  Max: 35
Metrics/ClassLength:
  Max: 200
Metrics/AbcSize:
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 15
