---
- client_id: exampleClient
  client_name: This is an example Client name
  client_uri: http://localhost:4200/about
  logo_uri: http://localhost:4200/logo.png
  tos_uri: http://localhost:4200/tos
  policy_uri: http://localhost:4200/privacy
  jwks_uri: http://localhost:4200/jwks.json
  software_id: IDK
  software_version: "1.2.3"
  redirect_uris:
  - http://localhost:4200/cb
  token_endpoint_auth_method: private_key_jwt
  grant_types:
  - authorization_code
  - client_credentials
  response_types:
  - code
  scope:
  - omejdn:write
  - openid
  contacts:
  - someperson@localhost:4200
  resource:
  - http://example.org
  attributes: []

- client_id: minimalClient
  redirect_uris:
  - http://localhost:4200/cb
  token_endpoint_auth_method: none
  scope:
  - profile
  - openid