---
- client_id: exampleClient
  client_name: An example Client
  grant_types: authorization_code
  client_uri: http://localhost:4200
  logo_uri: http://localhost:4200/assets/img/fhg.jpg
  tos_uri: http://localhost:4200
  policy_uri: http://localhost:4200
  software_id: MyAwesomeClient
  software_version: 1.0.0
  token_endpoint_auth_method: none
  redirect_uris: http://localhost:4200
  post_logout_redirect_uris: http://localhost:4200
  scope:
  - openid
  - omejdn:admin