---
## Welcome to Omejdn.
##
## Please have a look at the documentation first, if you have any questions.
## This is the main configuration file.
## Once you start Omejdn for the first time, the comments here will disappear
## and all non-specified values will be filled in with their default values.
## Omejdn is aware of any changes to this file and will always use the new configuration.

## Omejdn's Issuer Identifier.
## Please ensure that, assuming the issuer id is https://example.org/some/path,
## Omejdn's /.well-known/oauth-authorization-server endpoint is reachable as
## https://example.org/.well-known/oauth-authorization-server/some/path (per RFC 8414).
## To support dynamic OpenID clients, the same endpoint should be available as
## https://example.org/.well-known/openid-configuration/some/path and
## https://example.org/some/path/.well-known/openid-configuration for backwards compatibility.
#issuer: https://localhost:4567

## The URL where Omejdn's endpoints are mounted, in case it differs from `issuer`
#front_url: https://localhost:4567

## IP and (optionally) port to bind to
## Changes only apply after a restart
#bind_to: 0.0.0.0:4567

## CORS allow origin response value
## Changes only apply after a restart
#allow_origin: "*"

## Application Environment. Set to production to supress debug output
#app_env: debug

## Enable OpenID functionality (requires at least one user_db plugin)
#openid: false

## The default user_db plugin to use
#user_backend_default: 'yaml'

## Default `aud` value in tokens
#default_audience: ''

## Accept different values as `aud`
#accept_audience: https://localhost:4567

## Set expiration time and algorithm for each token
## Does not affect already issued tokens
#access_token:
#  expiration: 3600
#  algorithm: RS256
#id_token:
#  expiration: 3600
#  algorithm: RS256

## Plugins enable additional functionality.
## See the respective plugin for configuration options.
## Loading and unloading of plugins requires a restart
#plugins:
#  user_db:
#    yaml:
#      location: config/users.yml
#    sqlite:
#      location: config/users.db
#    ldap:
#      host: localhost
#      port: 636
#      base_dn: ''
#      uid_key: dn
#  api:
#    admin_v1:
#    user_selfservice_v1:
#      allow_deletion: true
#      allow_password_change: true
#      editable_attributes:
#        - email
#        - address
#        - phone_number
#  claim_mapper:
#    attribute:
#      skip_access_token: false
#      skip_id_token: false
